spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      min-idle: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml

knife4j:
  enable: true